Upgrade to Tritium 0.8.3 (#2642)
Bumps Tritium to 0.8.3 which restores backward compatibility for `LoggingInvocationHandler` constants.

* Restore types on `LoggingInvocationEventHandler` constants to `com.palantir.tritium.api.functions.LongPredicate`
Add explicit backward compatibility bridge constructors to `AbstractInvocationEventHandler` and `LoggingInvocationEventHandler`

This avoids potential `NoSuchFieldError`:
```
java.lang.NoSuchFieldError: LOG_DURATIONS_GREATER_THAN_1_MICROSECOND
    at com.palantir.atlasdb.util.AtlasDbMetrics.instrument(AtlasDbMetrics.java:77)
```

* Bridge to back compatibility

Introduce bridge method to maintain compatibility for `com.palantir.tritium.proxy.Instrumentation$Builder.withLogging(Lorg/slf4j/Logger;Lcom/palantir/tritium/event/log/LoggingLevel;Lcom/palantir/tritium/api/functions/LongPredicate;)Lcom/palantir/tritium/proxy/Instrumentation$Builder;` to avoid:

```
java.lang.NoSuchMethodError: com.palantir.tritium.proxy.Instrumentation$Builder.withLogging(Lorg/slf4j/Logger;Lcom/palantir/tritium/event/log/LoggingLevel;Lcom/palantir/tritium/api/functions/LongPredicate;)Lcom/palantir/tritium/proxy/Instrumentation$Builder;
    at com.palantir.atlasdb.util.AtlasDbMetrics.instrument(AtlasDbMetrics.java:76)
```