Upgrade gradle-baseline (#5044)
* Sort gradle plugins

* Add gradle-palantir-java-format

* Use gradle-baseline-java:3.43.0

* Run baselineUpdateConfig

* Apply gradle-palantir-java-format

* Use com.google.errorprone 2.4.0 and org.immutables 2.8.8

* Apply error-prone automated refactorings

* Temporarily relax error-prone constraints until we can fix all violations

* Use method reference to workaround error-prone compilation failure

/Volumes/git/palantir/atlasdb/atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java:1378: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
        assertThatExceptionOfType(TransactionLockTimeoutException.class).isThrownBy(() -> transaction.commit());
                                                                                    ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.4.0
     BugPattern: LambdaMethodReference
     Stack Trace:
     java.lang.NullPointerException
        at com.google.errorprone.fixes.SuggestedFixes.compilesWithFix(SuggestedFixes.java:1214)
        at com.google.errorprone.fixes.SuggestedFixes.compilesWithFix(SuggestedFixes.java:1100)
        at com.google.errorprone.fixes.SuggestedFixes.compilesWithFix(SuggestedFixes.java:1082)
        at com.palantir.baseline.errorprone.LambdaMethodReference.lambda$convertMethodInvocations$1(LambdaMethodReference.java:170)

* Add generated changelog entries

* Unpin checkstyle version

* Rely on gradle-baseline IntelliJ Idea defaults

Remove IntelliJ Idea overrides

* Suppress some checkstyle rules until they can be remediated

Fix up minor checkstyle violations

* Upgrade to gradle 6.7

* Standardize baseline configuration in build.gradle

* Remove changelog

* Update error-prone configuration (#5048)

* Update error-prone configuration

* Fix PreferCollectionConstructors

```
./gradlew compileJava compileTestJava -PerrorProneApply=PreferCollectionConstructors
./gradlew format
```

* Fix BracesRequired

`./gradlew compileJava compileTestJava -PerrorProneApply=BracesRequired && ./gradlew format`

* Fix LoggerEnclosingClass

`./gradlew compileJava compileTestJava -PerrorProneApply=LoggerEnclosingClass && ./gradlew format`

* Fix Slf4jLevelCheck

```
./gradlew compileJava compileTestJava -PerrorProneApply=Slf4jLevelCheck && ./gradlew format
```

* Fix ExecutorSubmitRunnableFutureIgnored

* Fix RedundantModifier

* Fix MissingOverride

* Fix LambdaMethodReference

* Fix FinalClass

* silence StrictUnusedVariable to avoid losing other signal

* Fix PreferStaticLoggers

* Fix UnnecessaryLambdaArgumentParentheses

* Fix BadImport

* Fix UnnecessaryParentheses

* remove unnecessary comments

* Disable JdkObsolete for now to reduce compilation spam

* More FinalClass fixes

* More MissingOverride

* Fix Incomparable

* Fix CollectionStreamForEach

* Fix StreamOfEmpty

* More LambdaMethodReference

* More BadImport

* More ClassCanBeStatic

* Suppress PreferStaticLoggers in ProfilingTimelockServiceTest

* Suppress static/final class on MaxTimestampsToGiveTimestampService

Required for mockito spies

* Suppress PreferStaticLoggers in TimestampAllocationFailuresTest

* format

Co-authored-by: Carter Kozak <ckozak@palantir.com>

* Fixup merge formatting

Co-authored-by: Carter Kozak <ckozak@ckozak.net>
Co-authored-by: Carter Kozak <ckozak@palantir.com>